src/sendquery.js

fix(query): coerce string number to int for limit

---

package-lock.json
package.json
src/index.js

feat(monitoring): adds epsagon for service monitoring

---

src/QueryExecutionError.js
src/sendquery.js
test/index.test.js
test/testSend.js

adds different error types for different error conditions
fixes #1

fix(index): report missing queries as 404

---

package-lock.json
package.json
src/index.js

Health check

---

package.json

This service should be monitored as part of _Delivery_.

chore(monitoring): moving to delivery group

---

src/env.js
src/sendquery.js

fix(index): removes potential problem of newlines

---

README.md
src/sendquery.js

some params are sent as strings; must parse into int

fix(query): param not parsed

---

README.md

Marquise rosier doc fix

---

package.json
src/index.js
src/queries/next-resource.sql
src/sendquery.js
src/util.js
test/index.test.js
test/testSend.js
test/testUtils.js

https://github.com/adobe/helix-run-query/issues/53

Publicize query

---

package-lock.json
package.json
src/util.js
test/testUtils.js

Table name replace

---

src/queries/next-resource.sql
src/queries/top-pages.sql
src/sendquery.js
src/util.js
test/testSend.js
test/testUtils.js

Date replace

---

src/index.js
src/queries/top-pages.sql
src/sendquery.js
src/util.js
test/index.test.js
test/testSend.js
test/testUtils.js

Auth top page

---

package.json
src/queries/top-blogposts.sql

a new query to see top pages being requested by users of theblog
fix #94

feat(queries): a query to see top blogs in theblog helix page

---

package-lock.json
src/index.js
src/queries/error500.sql
src/queries/next-resource.sql
src/queries/top-blogposts.sql
src/queries/top-pages.sql
src/sendquery.js
src/util.js
test/index.test.js
test/testSend.js

response contains playback properties: parameters, query description
fix #204

feat(index.js): response contain playback

---

src/queries/most-visited.sql

The deny-list of repos to be excluded is now kept in a separate table.

feat(most-visited): exclude repos

---

package-lock.json
package.json
src/index.js
src/util.js
test/post-deploy-utils.js
test/post-deploy.test.js
test/testQueries.js
test/testUtils.js

This is an odd fix for #433: the generated query had a syntax error, because in some cases line breaks in SQL are important. We used to strip them, which triggered this bug.
Why should you care? This bug is blocking the Helix Pages diff tests 😥

fix most visited

---

src/queries/rum-checkpoints.sql

- fix(checkpoints): avoid double listing of checkpoints when no generation parameter was provided
- fix(checkpoints): calculate percentages based on weight and not just on raw event count
```
tv dim: 31 x 4
checkpoint  events percent_dropoff percent_total
1     any         70125   0              100
2     top         31479  55.1             44.9
3     lcp         31212   0.8             44.5
4     cwv         29051   6.9             41.4
5     load        26593   8.5             37.9
6     unsupported 24607   7.5             35.1
7     noscript    7750   68.5             11.1
8     click       4325   44.2              6.2
9     top         4097    5.3              5.8
10    lcp         4087    0.2              5.8
11    load        3931    3.8              5.6
12    cwv         2785 …
```

fix checkpoint counter

---

src/queries/daily-pageviews.sql

I'm joining the results with a all possible dates within the range to create 0-valued rows instead of empty (or missing) roms
see https://cq-dev.slack.com/archives/C9KD0TT6G/p1641392248050500

fix(pageviews): coalesce empty values with 0 for dates without hits in the min/max range

---

src/queries/rum-sources.sql
src/queries/rum-targets.sql

- feat(rum): wip: rum sources
- feat(rum): get top targets for a checkpoint and source, split by separator and order by pageviews

more rum queries

---

src/queries/rum-dashboard.sql

Highlight the most popular new pages or pages with substantial traffic increase with parameter `rising: true`

Feature: Rising pages in RUM Dashboard

---

src/queries/rum-dashboard.sql
src/util.js
test/testUtils.js

- fix(rum-dashboard): do not coerce boolean into strings
- feat(api): automatically coerce boolean parameters

Coerce `rising` flag to boolean

---

package.json
src/queries/ee-score.sql

- build(deploy): include ee-score in executable queries
- fix(ee-score): exclude localhost from reports
- refactor(ee-score): no * select
- refactor(ee-score): remove unused ctes
- refactor(ee-score): rename `time` to `visittime` to avoid conflict with built-in function `TIME`

Include EE-Score in runnable queries

---

src/sendquery.js
test/fixtures/recordings/bigquery-tests_1831921034/runs-a-query-with-myrequest-replacer_3766853551/recording.har
test/fixtures/recordings/bigquery-tests_1831921034/runs-a-query-with-params_3960889146/recording.har
test/fixtures/recordings/bigquery-tests_1831921034/runs-a-query_980716932/recording.har

- chore: empty
- fix(query): do not assume data location anymore

fix: do not assume dataset location

---

src/queries/rum-experiments.sql

fix(experiments): don't count double clicks when determining conversion rate

---

src/queries/dev-urls.sql

otherwise you will see invalid tests like in https://github.com/hlxsites/nedbank/pull/48#issuecomment-1427466017

fix(dev-urls): do not include head.html in results

---

src/queries/dev-urls.sql

fixes https://github.com/adobe/helix-bot/issues/1057

fix(dev-urls): more effective exclusion of `head.html`

---

README.md

paragraph was indented, resulting in a code block
N/A

docs(readme): fix Parameterized Queries paragraph

---

src/queries/rum-checkpoint-urls.sql

Root case fix for #848 https://cq-dev.slack.com/archives/CGG9B79BK/p1680781196074679

fix(rum-checkpoint-urls): cast parameter as int

---

src/queries/rum-checkpoint-urls.sql

fix rum-checkpoint-urls limit

---

src/queries/rum-sources.sql

fix(rum-sources): added source filter

---

src/index.js

This is in preparation of the release of v3 and should be merged and released before #831 is merged.

feat(index): add deprecation header for upcoming v3

---

src/util.js
test/testUtils.js

do not allow arrays to pass through to the query

fix(utils.js): fix bug that enables arrays to pass

---

src/queries/rum-checkpoint-cwv-correlation.sql

- fix(cwv-correlations): use domain keys
- docs(cwv-correlations): add descriptions for all output parameters

fix correlations

---

README.md

Requesting review by Lars for content and Lydia for readability.

docs: readme update for developers

---

src/queries/rotate-domainkeys.sql

fix(rotate): don't allow accidental revocation

---

test/testQueries.js

test(rotate): add note to domain key rotation

---

package-lock.json
package.json
test/dev/server.js

- add dev server for running locally

chore: add dev server

---

.sqlfluff
package.json
src/queries/multi-results.sql
src/queries/rum-bundles.sql
test/testQueries.js

I'd still treat this as somewhat experimental after release, i.e. we can remove it without a breaking change.

feat(bundles): experimental raw data export for single day of data

---

package.json
src/queries/dash/add-lhs-data.sql
src/queries/rum-common.sql

Provides support for adding Lighthouse Data into Bigquery via Spacecat Audit Post Processor

add lhs webhook

---

src/queries/rum-forms-dashboard.sql

Adding Form type marketo also to capture form views and submission

---

src/queries/rum-sources.sql

Adding `&aggregate=false` will prevent the grouping which only shows `topurl`.  Calling without that param will result in as-is behavior for the `rum-sources` query for backward compatibility purposes.
Results pre-approved at `@ci7041` by @raji-unni and Iustin Popescu.

feat: add option to not aggregate rum-sources

---

src/queries/dash/domain-list.sql

#1111 feat: add AEM CS mapping information to domain list 

feat: add AEM CS mapping information to domain list #1111

---

package-lock.json
package.json
test/post-deploy.test.js

Fix post deploy tests #1146 
refactor tests to use plain mocha

 Fix post deploy tests #1146 

---

src/index.js
src/sendquery.js

[Feature] Log costs of a query to Coralogix #1143

Log costs per query and include domain key

---

src/queries/dash/domain-list.sql

#1140
Remove pv threshold, cleanup hostname and ims org id.
Thanks!

[feature] Remove from domain-list the page views threshold

---

src/sendquery.js
test/fixtures/recordings/Index-Tests_647266286/index-function-truncates-long-responses_2516890324/recording.har
test/fixtures/recordings/Index-Tests_647266286/index-returns-a-redirect-if-path-ends-with-chart_3410347873/recording.har
test/index.test.js

#1143 [Feature] Log costs of a query to Coralogix 
Refactoring done:
- Unified creation of job and stream
- Code that consumes the stream
- Always redact authorization headers in Polly recordings.

feat(sendquery): Enable cost logging for all jobs

---

src/queries/common-event-v5.sql

[RUM] Filter fake weights from EVENTS_V5 #1157 

feat(events_v5): ignore invalid weights in EVENTS_V5

---

package.json
src/queries/rum-forms-dashboard.sql
src/queries/rum-formsubmit-views.sql

Forms remove weight 1
