package-lock.json
package.json
src/index.js
src/sendquery.js
test/index.test.js
test/testSend.js

guesses the response size based on the average size of the first ten rows, then truncates the
response (and indicates that it did so)
fixes #2

fix(index): guard against too large response sizes

---

package.json

Monitoring setup for @adobe/helix-run-query was broken due to missing config.

fix(monitoring): adding back missing config

---

package.json
src/queries/error500.sql

new query that allows us to log 500s that fall through
https://github.com/adobe-private/project-helix/issues/443#issuecomment-603684182

feat(queries): added new query for error tracing

---

package.json
src/queries/recent-errors.sql
test/testQueries.js

This is a generalization of the `error500` query that works for any service ID (but requires authentication)

feat(queries): add generic last-errors query

---

package.json
src/queries/rum-dashboard.sql

adds a query that extracts share of good (according to Google limits) CWV values, average CWV values, estimated number of page views, and estimated share of total RUM traffic for the current and previous 30 day period for an owner-repo pair, a domain name, or all domains with Helix RUM collection set up
```bash
$ cat src/queries/rum-dashboard.sql | bq query --use_legacy_sql=false --format=prettyjson --parameter domain::- --parameter owner::- --parameter repo::- --parameter limit:INT64:3
```
```jsonc
[
{
"avgcls": "0.011", // average CLS for the current period
"avgcls_1": "0.038", // average CLS for the previous period
"avgfid": "2", 
"avgfid_1": "2", 
"avglcp": "912", 
"avglcp_1": "904", 
"clsgood": "68", // percentage of page views that result in a "good" CLS, according to Google in the …
```

feat(queries): Add RUM Dashboard

---

package.json
src/queries/blobs-served.sql

adds one query with following parameters: 
- `fromHours` range of hours to go back in time to aggregate data from (smaller values make faster and cheaper queries) -
- `status` status code of the requests to analyze 
- `limit` number of results to retrieve (results are ordered by frequency) 
- `offset` starting count for pagination
fixes #477
Example:
```bash
$ cat src/queries/blobs-served.sql | bq query --use_legacy_sql=false --parameter fromHours:INT64:720 --parameter status::200 --parameter limit:INT64:10 --parameter offset:INT64:0  --format=prettyjson
```
```jsonc
[
{
"earliestreq": "2021-07-20 01:22:43", // timestamp of the earliest request matching
"format": "png",
"host": "theblog--adobe.hlx.page", // example host name that served the blob (note that it can contain a branch name) …
```

feat(sql): create queries for media migration

---

package.json
src/queries/daily-pageviews.sql
test/testSend.js

shows the daily page views for the `url` (domain name and optional path) for the last `limit` days (default 30), starting at `offset` (default 0, i.e. today)
Try it here: https://helix-pages.anywhere.run/helix-services/run-query@ci2518/daily-pageviews?url=blog.adobe.com/en&limit=3&offset=1

feat(queries): add daily page views report

---

package.json
src/queries/blobs-served-hlx3.sql

@trieloff  is this correct?
apparently not:
```
{
"owner": "adobe",
"repo": "theblog",
"id": "10081ac113dbd24000d2aa05c1bd29abc5e45e0c",
"format": "jpg",
"latestreq": {
"value": "2021-09-05T23:19:49.632Z"
},
"earliestreq": {
"value": "2021-09-05T23:19:49.632Z"
},
"requests": 1,
"host": "theblog--adobe.hlx.page"
},
```

feat: add blobs-served query for helix3

---

src/queries/rum-dashboard.sql

Removed `p` from fid key in rum dashboard result
#504

fix(queries): fix typo in rum dashboard result, change 'fidp' to 'fid'  

---

package.json
src/queries/guess-hostname.sql

run this query with either a `domain` parameter or `owner` and `repo` (`ref` optional) to get the most frequent matching combinations based on referrer data. As we do not have forwarded-host data, using (and cleaning) referrer data is the best guess we can make, although not 100% bullet-proof.

feat(hlx3): add hostname guesser

---

src/queries/rum-dashboard.sql

by using a FULL OUTER JOIN, records with missing data in either period will no longer be stripped, but simply show `null` values

fix(rum-dashboard): show data even when there is no data in current or previous period

---

package.json
src/queries/content-power-curve.sql

this query shows how many distinct URLs (reach) have been sending RUM data continuously for how many days (persistence)

feat(queries): add content-power query

---

src/queries/rum-dashboard.sql

pages are now always ordered by current page views, then by previous page views. `Other` always comes last

fix(rum-dashboard): fix ordering of pages

---

package.json
src/queries/rum-common.sql
src/queries/rum-experiments.sql

The new `rum-experiments` query endpoint supports following parameters:
- `domain`: hostname where experiments are running, use the canonical URL to prevent contamination from staging and dev
- `interval`: how many days of history to consider (default: 30)
- `offset`: move the window of data to be considered by so many days to the past (default: 0)
- `timezone`: timezone to use for full date cut-offs (default: GMT)
- `experiment`: only pull results for one single experiment (default: -, i.e. all)
- `conversioncheckpoint`: this checkpoint will be considered a successful conversion (default: click)
It will report results as follows:
```json
[
{
"control_conversion_events": "1",
"control_conversion_rate": "0.166666667",
"control_conversions": "1",
"control_experimentation_events": "6", …
```

Report Experiment Conversion using RUM data

---

src/queries/most-visited-hlx3.sql

Try 
- https://helix-pages.anywhere.run/helix-services/run-query@ci3743/most-visited-hlx3?limit=10&version=v7&threshold=0
- https://helix-pages.anywhere.run/helix-services/run-query@ci3743/most-visited-hlx3?limit=10&version=v6&threshold=0
@tripodsan the `threshold` parameter can be dropped as we gather more data.

Version filter for most visited query

---

src/queries/rum-sources.sql

this should fix the `checkpoint=404` issues

fix(rum-sources): make sure checkpoint is always treated as a string

---

src/queries/rum-sources-targets.sql

force checkpoint to be STRING, not INT64

fix to allow checkpoint 404

---

README.md
dev.sh
src/queries/rum-experiments.sql

In low traffic settings, a scenario could arise where for a given experiment the `control` variant was never shown.
This would cause the whole experiment to disappear from reporting. The fix in this PR is to create a synthetic row
for each experiment, fill it with the real `control` values if available or `NULL` otherwise.
This also required changing the divisions to a safe division, so that for some experiments conversion rates, etc.
will be reported as `NULL` now

Fix RUM Experiments for low traffic experiments

---

src/index.js
src/queries/rum-dashboard.sql
src/sendquery.js
src/util.js
test/index.test.js
test/post-deploy.test.js
test/testQueries.js
test/testSend.js
test/testUtils.js

This PR provides the ability to return column descriptions in the `meta` worksheet of the response.
As a query developer, you add colon-separated column names and their description at the bottom of the query SQL, similar to the parameter description at the top of the SQL file. The query engine will then pick this up and return it as part of the response object, making deciphering the responses a bit easier.

Extended Metadata in Responses

---

src/index.js
src/util.js
test/testUtils.js

Added support for folders under /src/queries to enable better organization.  Supports a variety of URL formats as described in the comments of the first commit.

support query folders using standard path separator (/)

---

src/util.js
test/testUtils.js

adjusted the query folder regular expression and added a test for another valid path format:
`/helix-services/run-query/3.3.0/folder/folder/file`

query folders - allow semantic version url used by postdeploy test

---

src/queries/rotate-domainkeys.sql

Franklin Dashboard can expose a domainkey generate feature, but first this run-query needs to be available to be called from it.

allow rotate-domainkeys to be called from website

---

package.json
src/queries/rum-pageviews-pivot.sql

Several people have asked in the past weeks to see traffic numbers across sites.  This new query shows the past 12 month total estimated page views per domain where at least one of the past 3 months has >= 1000 estimated page views.  The syntax is a bit different than most queries due to the PIVOT command accepting dynamic column names.  EXECUTE IMMEDIATE is used to convert a dynamic list into a static string, and variable/param replacement are different.

new query - monthly totals across sites, pivot table

---

package.json
src/queries/revoke-domainkey.sql
src/queries/rotate-domainkeys.sql

Outside of the PR:
- added additional metadata fields (create_date, parent_key_bytes, note) to helix_reporting.domain_keys
- added ROTATE_DOMAIN_KEYS stored proc to helix_reporting dataset and added note param
- updated helix_rum.ROTATE_DOMAIN_KEYS to populate note field with "legacy" until such time we remove from that dataset -- probably by EOY if we no longer see any where note=legacy it will be safe to delete the old stored proc from helix_rum.
- added helix_reporting.REVOKE_DOMAIN_KEY stored proc which revokes a domain key without replacing it
Inside the PR:
- updated rotate-domainkeys run-query to point to replacement stored proc in new dataset, add note param
- new run-query for revoke
Two additional metadata fields are auto-populated by the stored proc without any related …

feat(domainkey): add metadata, revoke w/o create

---

src/queries/rum-pageviews.sql

The rum-pageviews query has a default offset of 0, which incorrectly switched to a date-range based query when the default offset was not overwritten in the call.  More details at #993.  This fix ensures that the default offset works as expected.  To see the fix in action before the merge, call `run-query@ci6681/rum-pageviews.sql` instead of `run-query@v3/rum-pageviews.sql` without the offset param.
cc: @iuliag 
#993

fix: prevent negative offset for pageviews query

---

src/queries/rum-pageviews.sql

This is a massive refactoring, and simplification, borrowing the filtering from #1053
It drops the support for `granularity=auto` so we probably have to declare this a breaking change, even if the impact is much smaller than the last breaking change we had.
It also partially reverts the changes made in #1039, negative offsets are now possible again, so that you can use `startdate` and `enddate` parameters

feat(pageviews): enable filters for checkpoint, source, and target

---

dev.sh
src/queries/rum-pageviews.sql

If the current time period is still in progress, then data visualizations often look bad
because they show a drop in the current day, week, quarter, etc. This commit adds a simple
forecast for the current period based on a heuristic that is giving 50% weight to the
current period's data and 50% to the past seven data points, so that a more accurate estimate
can be provided
```
./dev.sh rum-pageviews url www.aem.live granularity 7
Waiting on bqjob_r3cefbe447a319e1c_0000018db2325afd_1 ... (0s) Current status: DONE
year   month   day            time            url   pageviews   pageviews_forecast   url_forecast
------ ------- ----- ------------------------ ----- ----------- -------------------- --------------
2024       2    12   2024-02-12 00:00:00+00    34        8552                10470 …
```

feat(pageviews): add a a pageview and url forecast for the current time period

---

src/queries/rum-checkpoint-urls.sql
src/queries/rum-content-requests.sql
src/queries/rum-pageviews.sql
src/queries/rum-targets.sql

Some run-queries do not handle timezone consistently.  The most obvious case is for a one-day query which returns two results.
Old: https://helix-pages.anywhere.run/helix-services/run-query@v3/rum-pageviews?url=www.aem.live&domainkey=d77c830d-3ec9-4611-8b86-256346fa7659&interval=-1&offset=-1&startdate=2024-02-20&enddate=2024-02-21&timezone=America/New_York
New: https://helix-pages.anywhere.run/helix-services/run-query@ci6895/rum-pageviews?url=www.aem.live&domainkey=d77c830d-3ec9-4611-8b86-256346fa7659&interval=-1&offset=-1&startdate=2024-02-20&enddate=2024-02-21&timezone=America/New_York
Note: There is a separate issue around EVENTS_V3 in which a one-day query can return two days, if the `time` field is exactly on the midnight hour.  You can see this by replacing `America/New_York` in the …

fix: add timezone to date functions

---

src/queries/common-event-v5.sql
src/queries/dash/domain-list.sql
src/queries/ee-score.sql
src/queries/rum-bounces.sql
src/queries/rum-checkpoint-cwv-correlation.sql
src/queries/rum-checkpoint-urls.sql
src/queries/rum-checkpoints.sql
src/queries/rum-content-requests.sql
src/queries/rum-dashboard.sql
src/queries/rum-experiments.sql
src/queries/rum-intervals.sql
src/queries/rum-pageviews-pivot.sql
src/queries/rum-pageviews.sql
src/queries/rum-sources-targets.sql
src/queries/rum-sources.sql
src/queries/rum-targets.sql

Two benefits from this PR:
1) Combine cloudflare- and fastly-sourced RUM data
2) Change so that `enddate` includes information from that date for date-based queries
`ci6936` has these changes.  I will test all before merging.  Given so many queries were touched, to avoid merge conflicts I ask you to not work on other run-query changes until after this is merged.  Please review and comment now, but I will handle the merge.

feat: upgrade run-queries to use _V5 table functions

---

src/queries/rum-common.sql

As part of the RUM for AEM CS initiative, we are getting requests for 100s of domains to share a single domain key.  It would be a nice convenience to create the domain key for all domains in one request.
This PR is to document and discuss a change to the table function helix_reporting.ROTATE_DOMAIN_KEYS which is a pre-requisite to a run-query change.  Upon approval, I will make the table function change in BigQuery and move on to the run-query changes.
This change is backward compatible -- a single domain may still be passed in.  A test implementation exists at helix_reporting.ROTATE_DOMAIN_KEYS_MULTIPLE for now.
```
CALL helix_reporting.ROTATE_DOMAIN_KEYS_MULTIPLE(
'<uber_domain_key>',
'<domain or comma-separated domain list>',
'UTC',
-1,
'-',
'<desired domain key>',
true, …
```

feat: backend to add key to multiple domains in one call

---

src/queries/rum-common.sql

Small fix to improve integrity of domain key generation -- specifically to remove spaces and prevent a trailing comma from creating a global domain key.  Already pushed to table function, this is just for documentation purposes.

fix: prevent spaces or trailing comma in multi-domain key generation

---

package.json
src/queries/rum-forms-dashboard.sql

New run-query for Forms team.  Limited mashup of three calls to two existing queries -- rum-checkpoint-urls x 2 and rum-dashboard x 1.  Includes form views, form submissions, and core web vitals in one query.
Example at https://helix-pages.anywhere.run/helix-services/run-query@ci7006/rum-forms-dashboard?url=www.aem.live&domainkey=d77c830d-3ec9-4611-8b86-256346fa7659

Forms dashboard

---

src/queries/rum-forms-dashboard.sql

Fix to return INP, LCP, FID as integers - aligned with how rum-dashboard behaves.

fix: cast cwv as int64

---

src/queries/common-event-v5.sql

RUM collection adds padding to the current time for PII purposes.  See https://github.com/adobe/helix-rum-collector/blob/main/src/utils.mjs#L29
With the addition of hourly-based reporting for the current day, this can lead to the appearance of future events which will raise questions among users.  Decision was made to exclude future events from reporting.

fix: exclude future events

---

src/queries/rum-bundles.sql
src/sendquery.js

This will make sure that `rum-bundles` response does not vary with repeated executions
- fix(bundles): sort bundles by date
- fix(sendquery): bump response size limit to 6MB

Stable Bundles

---

src/queries/rum-bundles.sql
test/testQueries.js

pagination uses the `after` and `limit` URL parameters and prevents response sizes from
getting too big. Run the query a first time without the `after` URL parameter and it will
return the first `limit` rows. After that, take the value of `id` of the last record received
and use it as the value of the `after` URL parameter. Repeat the process until no more rows
are returned

feat(bundles): enable pagination

---

src/queries/rum-pageviews.sql

Cedric and Ekrem noticed that the page views chart in the datadesk dashboard looked choppy.  Further investigation showed this was due to the presence of duplicate dates which were offset by one hour when the date range overlapped with a daylight savings change -- one of the duplicate dates always showed 0 page views.  You can see this at https://helix-pages.anywhere.run/helix-services/run-query@v3/rum-pageviews?url=www.aem.live&domainkey=d77c830d-3ec9-4611-8b86-256346fa7659&startdate=2024-03-07&enddate=2024-03-14&timezone=America%2FLos_Angeles&interval=-1&offset=-1 with different data behavior around the daylight savings shift the weekend of March 11.
This issue is due to a combination of factors:
1) The addition of timezone functionality in the dashboard.  The default "timezone" UTC is …

fix: daylight savings placeholder

---

package.json
src/queries/rum-404.sql

New query for 404s.  The one currently used by the dashboard groups by source, shows the top url for the source, and that has led to questions around data mismatches.  See https://github.com/adobe/franklin-dashboard/issues/66.
Test at https://helix-pages.anywhere.run/helix-services/run-query@ci7231/rum-404 with a url and domain key which is known to have 404 data.

feat: new 404 query grouped by url with source count

---

src/queries/common-event-v5.sql
src/queries/rum-common.sql

This proposed change is to the foundational EVENTS_V5 table function.  Upon merging, I will make the change directly in BigQuery.
Currently the url param assumes one domain or url.  You can see the logic around matching the param with the domain key hostname prefix (alongside various prefix and suffix CONCAT logic) as well as splitting the param into multiple parts to match against the event hostname field.
The proposed change is based on a requirement for the new content requests run-query to accept a comma-separated list of domains and return data for each (cc: @lydiapuric).  There were a few indentation adjustments but two core changes:
- The first is to match each domain in the comma-separated list against the domain key, and events are only returned if the given domain key is valid …

feat: allow comma-separated list of domains as input param

---

src/queries/rum-common.sql

https://github.com/adobe/helix-rum-collector/pull/301 introduced new user agent types.  This follows a reduction in user agent types several months ago which made the CLUSTER_FILTERCLASS function out of date.  Upon approval and merge, I will add the new implementation for the function in BigQuery.

adjust CLUSTER_FILTERCLASS to be compatible with newly defined user agent types

---

package.json
src/queries/dash/edge-delivery-live-hints.sql

This query shows domains (with certain exclusions per the SQL) which had their first RUM collection in at least 30 days.  This is used as a hint that the domain might have gone live yesterday.  Spacecat will call it once per day and use it to augment data from other sources.
`https://helix-pages.anywhere.run/helix-services/run-query@ci7450/dash/edge-delivery-live-hints?domainkey=<global_domain_key>`

Go-live hints for spacecat

---

src/queries/rum-dashboard.sql
test/post-deploy.test.js
test/testQueries.js
test/testUtils.js

Add TTFB to rum-dashboard query.  The data already exists, just not currently available in API.
Before: http://helix-pages.anywhere.run/helix-services/run-query@v3/rum-dashboard?url=www.aem.live/home&domainkey=d77c830d-3ec9-4611-8b86-256346fa7659
After: http://helix-pages.anywhere.run/helix-services/run-query@ci7508/rum-dashboard?url=www.aem.live/home&domainkey=d77c830d-3ec9-4611-8b86-256346fa7659
#1116

Add TTFB to rum-dashboard

---

src/queries/dash/domain-list.sql

[Domain-list] hostname in response is not unique #1120 

[Domain-list] hostname in response is not unique #1120

---

src/queries/rum-dashboard.sql

Added short-circuit to prevent main query from running if the domainkey+url combination is invalid.  The existing implementation scans a lot of data even if the domain key is known to be invalid.
If satisfied, we can roll this out to other run-queries.  So far I could not find a way to handle this more narrowly only in EVENTS_V5.
Test at `/run-query@ci7821/rum-dashboard`.  My testing showed identical results for both valid and invalid domainkeys between `v3` and `ci7821`.

fix: short-circuit rum-dashboard query if invalid domain key

---

src/queries/multi-results.sql
src/queries/rum-dashboard.sql
src/sendquery.js

Pre-validate domain key for queries per guidance from Lars.  While making this PR, I removed the special handling within /rum-dashboard so that it goes through the same treatment as other queries.
I tested against several queries with `ci7978` which contains this change.  With a valid domain key, it returns the same as `v3`, and a bit slow.  With an invalid domain key, it returns valid JSON with no results very quickly.

pre-validate domain key for queries

---

src/queries/rum-content-requests.sql
test/testContentRequests.js

Updated exclusion list to better match CDN counting logic, most specifically to not count /libs/ JSON files as API calls.

update exclusion list for content request API calls
